# Generated by Django 4.2.11 on 2026-01-31 19:40

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=128)),
                ('user_profile_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='user_profile_image')),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expiry_time', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('video_title', models.CharField(max_length=100)),
                ('video_description', models.TextField()),
                ('video_banner', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='user_video_banner')),
                ('video_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='user_video')),
                ('video_upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
        ),
    ]
