# Generated by Django 4.2.11 on 2026-02-10 07:19

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255)),
                ('post_description', models.TextField()),
                ('post_images', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='user_post_images')),
                ('post_created_datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
        ),
    ]
